### ISSUE TITLE
Error detected while processing taskwiki/ftplugin/vimwiki/taskwiki.vim line 33

### ISSUE THREAD

**Issue by ahillio** [tools-life/taskwiki#301]
Hello Dear People!  I was happily in love with taskwiki and suddenly we started experiencing unexplainable (to my eyes) difficulties...

```
Traceback (most recent call last):
File "<string>", line 1, in <module>
NameError: name 'Mappings' is not defined
```
and...
```
Error detected while processing /home/alec/.dotfiles/vim/bundle/taskwiki/ftplugin/vimwi
ki/taskwiki.vim:
line   33:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/main.py", line 15, in <module
>
    from taskwiki import cache as cache_module
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/cache.py", line 5, in <module
>
    from taskwiki import preset
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/preset.py", line 5, in <modul
e>
    from taskwiki import util
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/util.py", line 6, in <module>

    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3250, in <modul
e>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3234, in _call_
aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3278, in _initi
alize_master_working_set
    for dist in working_set
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3278, in <genex
pr>
    for dist in working_set
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2785, in activa
te
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2284, in declar
e_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2201, in _handl
e_ns
    loader = importer.find_module(packageName)
AttributeError: module 'vim' has no attribute 'find_module'
```
are the errors I've found, the former is much more common than the latter.

The result is that vimwiki links can't be followed.  So vimwiki becomes largely broken.  I can only restore the link functionality to vimwiki by deleting taskwiki altogether, which leaves me not just brokenhearted but also more inconvenienced and less productive.

I've tried cloning the repo again and using the head of the master branch.  And I've tried checking out the 1.0.0 tag to use that state of code.  But neither of those give me a usable vimwiki, and I still have to remove taskwiki to get the base functionality (minus tasks) back.

**Comment by ahillio** [comment]
I'm getting that same error but now with a couple new lines at the end regarding cache:
```
Error detected while processing /home/alec/.dotfiles/vim/bundle/taskwiki/ftplugin/vimwiki/taskwiki.vim:
line   33:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/main.py", line 15, in <module>
    from taskwiki import cache as cache_module
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/cache.py", line 5, in <module>
    from taskwiki import preset
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/preset.py", line 5, in <module>
    from taskwiki import util
  File "/home/alec/.dotfiles/vim/bundle/taskwiki/taskwiki/util.py", line 6, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3278, in _initialize_master_working_set
    for dist in working_set
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3278, in <genexpr>
    for dist in working_set
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2785, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2284, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2201, in _handle_ns
    loader = importer.find_module(packageName)
AttributeError: module 'vim' has no attribute 'find_module'
Error detected while processing BufEnter Autocommands for "*.mkd":
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cache' is not defined
```

**Comment by vegsplore** [comment]
Got something similar yesterday. My whole setup somehow refused to work [probably] after an update. 

apt remove python3-tasklib; pip install tasklib

solved it for me on Debian testing. Hope it helps.

**Comment by liskin** [comment]
@vegsplore That is an unrelated issue: https://github.com/tools-life/taskwiki/commit/5032d0d74f2b63890784cd4e4392c21812952b05#commitcomment-42422040

(And I don't think it's a good idea to just `pip install` stuff globally. That will come to bite you later in unexpected ways. The only safe options are the distro package manager or virtualenv, the former being preferred.)

**Comment by ahillio** [comment]
@vegsplore I suspected this might be the case... and your mention of it (thanks!) motivated my to dig into pip (which I'm not so familiar with) to see what was installed.  Re-installing tasklib eliminated the error and returned some basic functionality around tasks but I'm still seeing issues with viewports and preset headers :/
