### ISSUE TITLE
Error when task has a due date

### ISSUE THREAD

**Issue by fiplox** [tools-life/taskwiki#357]
I've been using taskwiki on debian with no problem. Today I installed arch and get this error message when a task has due date:
```
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/nvim/plugged/taskwiki/taskwiki/errors.py", line 26, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/user/.config/nvim/plugged/taskwiki/taskwiki/decorators.py", line 10, in wrapped_function
    original_function(*args, **kwargs)
  File "/home/user/.config/nvim/plugged/taskwiki/taskwiki/main.py", line 60, in update_to_tw
    c.load_vwtasks()
  File "/home/user/.config/nvim/plugged/taskwiki/taskwiki/cache.py", line 181, in load_vwtasks
    self.vwtask[i]  # Loads the line into the cache
  File "/home/user/.config/nvim/plugged/taskwiki/taskwiki/store.py", line 58, in __getitem__
    item = self.get_method(key)
  File "/home/user/.config/nvim/plugged/taskwiki/taskwiki/store.py", line 128, in get_method
    return vwtask.VimwikiTask.from_line(self.cache, line)
  File "/home/user/.config/nvim/plugged/taskwiki/taskwiki/vwtask.py", line 152, in from_line
    self.task['due'] = parsed_due
  File "/usr/lib/python3.9/site-packages/tasklib/task.py", line 104, in __setitem__
    value = self._normalize(key, value)
  File "/usr/lib/python3.9/site-packages/tasklib/serializing.py", line 68, in _normalize
    return normalize_func(value)
  File "/usr/lib/python3.9/site-packages/tasklib/serializing.py", line 132, in normalize_due
    return self.datetime_normalizer(value)
  File "/usr/lib/python3.9/site-packages/tasklib/serializing.py", line 233, in datetime_normalizer
    localized = local_zone.localize(value)
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'
```

I'm using neovim 0.5

**Comment by fiplox** [comment]
Closing. See [tasklib issue](https://github.com/robgolding/tasklib/issues/94)
