### ISSUE TITLE
Error message at startup

### ISSUE THREAD

**Issue by arooni** [tools-life/taskwiki#446]
```
<SNR>1_LoadFTPlugin[19]..script  Error detected while processing BufReadPost Autocommands for "*.wiki"..function <SNR>65_setup_new_wiki_buffer[19]..vimwiki#u#ft_set[9]..FileType Autocommands for "*"..funct
ion <SNR>1_LoadFTPlugin[19]..script /Users/david/.vim/plugged/taskwiki/ftplugin/vimwiki/taskwiki.vim[29]..function provider#python3#Call:
line   18:
Error invoking 'python_execute_file' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "/Users/david/.vim/plugged/taskwiki/taskwiki/main.py", line 15, in <module>
    from taskwiki import cache as cache_module
  File "/Users/david/.vim/plugged/taskwiki/taskwiki/cache.py", line 5, in <module>
    from taskwiki import preset
  File "/Users/david/.vim/plugged/taskwiki/taskwiki/preset.py", line 5, in <module>
    from taskwiki import util
  File "/Users/david/.vim/plugged/taskwiki/taskwiki/util.py", line 3, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'WholeBuffer' is not defined
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cache' is not defined
Press ENTER or type command to continue

```

heres nvim's checkhealth:
```

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /usr/local/Cellar/neovim/0.9.5/share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=^H`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $TERM_PROGRAM="tmux"
- $COLORTERM="truecolor"

tmux ~
- OK escape-time: 1
- OK focus-events: on
- $TERM: screen-256color
- WARNING Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
  - ADVICE:
    - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
      set-option -sa terminal-features ',XXX:RGB'
    - For older tmux versions use this instead:
      set-option -ga terminal-overrides ',XXX:Tc'

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: pbcopy

Python 3 provider (optional) ~
- pyenv: Path: /usr/local/Cellar/pyenv/2.4.0/libexec/pyenv
- pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
- pyenv: Root: /Users/david/.pyenv
- `g:python3_host_prog` is not set.  Searching for python3.10 in the environment.
- WARNING pyenv is not set up optimally.
  - ADVICE:
    - Create a virtualenv specifically for Nvim using pyenv, and set `g:python3_host_prog`.  This will avoid the need to install the pynvim module in each version/virtualenv.
- Executable: /usr/local/bin/python3.10
- Python version: 3.10.14
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Disabled (g:loaded_ruby_provider=0).

Node.js provider (optional) ~
- Disabled (g:loaded_node_provider=0).

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /Users/david/.local/state/nvim/lsp.log
- Log size: 0 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: c          ABI: 14, path: /usr/local/Cellar/neovim/0.9.5/lib/nvim/parser/c.so
- OK Parser: lua        ABI: 14, path: /usr/local/Cellar/neovim/0.9.5/lib/nvim/parser/lua.so
- OK Parser: query      ABI: 14, path: /usr/local/Cellar/neovim/0.9.5/lib/nvim/parser/query.so
- OK Parser: vim        ABI: 14, path: /usr/local/Cellar/neovim/0.9.5/lib/nvim/parser/vim.so
- OK Parser: vimdoc     ABI: 14, path: /usr/local/Cellar/neovim/0.9.5/lib/nvim/parser/vimdoc.so

```

**Comment by arooni** [comment]
I did try reinstalling the taskwarrior neovim plugin.  And updating pynvim.  No dice.

**Comment by FelipeMarcelino** [comment]
Same here!

**Comment by yongli-abc** [comment]
It's missing the `packaging` module. Install that with pip in the corresponding virtual env.

**Comment by KUKARAF** [comment]
On debian based systems i had to install     python3-tasklib    python3-six and    python3-packaging perhaps this is worth including in the readme?
